const list = [
  {
    id: 1,
    nom: "Princi burger",
    description: "Viandes,frommages,Sauce bechamelle",
    prix: 25,
    img: "src/image/litoburger.jpg",
  },
  {
    id: 2,
    nom: "Pizza maison",
    description: "4Frommages,Viande,Poulet,Fruits de mer,Mortadelle,Oeufs durs",
    prix: 30,
    img: "src/image/pizzalito.jpg",
  },
  {
    id: 3,
    nom: "Soupe Machirou",
    description: "Viandes,vantans,Filets de poisson",
    prix: 20,
    img: "src/image/SOUPELITO.jpg",
  },
  {
    id: 4,
    nom: "Brochette Lito",
    description: "Viandes,Legumes,Sauces",
    prix: 5,
    img: "src/image/brochettelito.jpg",
  },
  {
    id: 5,
    nom: "Kebab Bunny",
    description: "Viandes en tranche,Sauce tomate",
    prix: 10,
    img: "src/image/kebab dnl.jpg",
  },
  {
    id: 6,
    nom: "bolog-naj",
    description: "Spaghetti,pure de tomate, mayonnaise,fromage",
    prix: 15,
    img: "src/image/min-sao lito.jpg",
  },
  {
    id: 7,
    nom: "Christo Tacos",
    description: "viandes,poulets,fromages,legumes,sauce maison",
    prix: 25,
    img: "src/image/tacos lito.jpg",
  },
  {
    id: 8,
    nom: "Chicken Vic",
    description: "poulets,sauce tomate pimente",
    prix: 20,
    img: "src/image/nuggets lito.jpg",
  },
  {
    id: 9,
    nom: "Sushi ",
    description: "lorem ipsum dolor sit amet",
    prix: 30,
    img: "src/image/sushi lito.jpg",
  },
  //     {
  //       id: 10,
  //       nom: "Soupe Legume",
  //       description: "lorem ipsum dolor sit amet",
  //       prix: 20000,
  //       img: "/src/image/Bolonaise.jpg",
  //     },
  //     {
  //       id: 11,
  //       nom: "Soupe Legume",
  //       description: "lorem ipsum dolor sit amet",
  //       prix: 20000,
  //       img: "/src/image/Bolonaise.jpg",
  //     },
  //     {
  //       id: 12,
  //       nom: "Soupe Legume",
  //       description: "lorem ipsum dolor sit amet",
  //       prix: 20000,
  //       img: "/src/image/Bolonaise.jpg",
  //     },
];

export default list;
